apiVersion: v1
kind: Service
metadata:
  name: riak
  namespace: default
  labels:
    app: riak
spec:
  selector:
    app: riak
    role: node
  ports:
  - port: 8087
    targetPort: 8087
    name: protobuf
    protocol: TCP

  - port: 8098
    targetPort: 8098
    name: http
    protocol: TCP
  type: NodePort
